# Generated by Django 4.1.3 on 2022-12-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
    ]
