# Generated by Django 4.1.3 on 2022-12-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_email_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_confirm',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвердил почту'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_password',
            field=models.BooleanField(default=False, verbose_name='Пользователь меняет пароль'),
        ),
    ]
