# Generated by Django 4.1.3 on 2022-12-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_email_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_url',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
