# Generated by Django 4.1.3 on 2022-12-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('administrator', 'Check_post_comments')]},
        ),
    ]
