# Generated by Django 4.1.3 on 2023-01-17 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_customuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='Подписчики', through='user.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
